spring:
  cloud:
    gateway:
      routes:
        ## MS-1
        - id: ms-1
          uri: http://localhost:8083/ms1
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=0
        ## ms-2
        - id: ms-2
          uri: http://localhost:8082/ms2
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=0


  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/fzkattendance
    username: root
    url: jdbc:mysql://localhost:3306/fzkattendance
    password: root
    jpa:
      hibernate:
        ddl-auto: none

server:
  port: 8084

