spring:
  cloud:
    gateway:
      routes:
        ## MS-1
        - id: ms-1
          uri: lb://ms-1
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=1
        ## ms-2
        - id: ms-2
          uri: lb://ms-2
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka