spring:
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/taskscheduler
    username: root
    url: jdbc:mysql://localhost:3306/taskscheduler
    password: root
    jpa:
      hibernate:
        ddl-auto: none
